---
title: "Ron Sarafian"
output: html_document
---

# Ron Sarafian

Ph.D. student at Dept. of Industrial Engineering at Ben Gurion University, 
Supervised by [Dr Jonathan Rosenblatt](http://www.john-ros.com/) and [Prof Itai Kloog](http://in.bgu.ac.il/en/humsos/geog/Pages/staff/kloog.aspx). 
My research focuses on statistical and machine learning algorithms and their application in geographical and environmental fields.

I am interested in solving both theoretical and real-world problems related to:

- Spatio-temporal data analysis
- Remote sensing based prediction 
- Multivariate statistics
- Distributed Machine Learning


# Projects

check my [Github page](https://github.com/ronsarafian) for projects in progress.

More cool stuff including some tutorials i wrote can be found in my [Rpub page](http://rpubs.com/ronsar)


# Education

<div class="row">
  <div class="col-sm-3">

2017 - Now 

2014 - 2016

2011 - 2014
</div>

  <div class="col-sm-9">

Ph.D. student, Ben-Gurion University of the Negev

MA. Economics (expertise in applied econometrics), The Hebrew University of Jerusalem
    + Thesis: Empirical estimation of government R&D policy with Machine Learning tools.
    + Advisor: Prof Shaol Lach
    
BA. Economics (summa cum laude), Ben-Gurion University of the Negev

</div>



# Experience

           | 
----------- ----------
2017 - Now  | bla
2014 - 2916 | OCS

bla


